### ISSUE TITLE
state not saved between browser sessions

### ISSUE THREAD

**Issue by drherman** [wolfman2000/stumpy#59]
Hi,

Dunno if bug or "missing feature".

When I close-reopen my browser, the state of the tracker is not saved so i'm "forced" to take screenshots when I don't want to play in one continuous session.

**Comment by wolfman2000** [comment]
That is a missing feature as stated in the README file. I don't know when I will get to that.

**Comment by CWSpear** [comment]
Would you be willing to take a PR on this?

I started adding some support. I currently have it saving Items and Dungeon states, and it appears to be working.

I was planning on having it update the URL, which means I want the serialization as short as possible, which means it's indexed based (which gets us a much shorter URL, but is fragile and more easily broken in updates).

e.g.

```
?dungeons=[[0,2,0,false,false,0,2,0,0],[3,6,1,false,false,0,3,1,0],[2,6,2,false,false,0,3,1,0],[2,6,3,false,false,0,3,1,0],[3,14,3,false,false,0,11,2,0],[6,10,5,false,false,0,7,2,0],[2,8,6,false,false,0,5,1,0],[4,8,7,false,false,0,5,1,0],[3,8,8,false,false,0,5,1,0],[0,8,1,true,false,0,5,2,2],[5,12,10,false,false,0,9,1,1],[20,27,11,false,false,0,24,0,0]]&items=[0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,-1,-1,0]
```

etc, etc.

**Comment by CWSpear** [comment]
See PR: https://github.com/wolfman2000/stumpy/pull/94

**Comment by milochristiansen** [comment]
This missing feature is a major show stopper for me using this tracker. I'm a casual rando player, so a run often takes several days. Any restart/crash/etc is a disaster, particularly since I often play keysanity.

I'm not too hyped about saving state in the URL though, local storage is there for a reason. Still, any solution is better than no solution.
