### ISSUE TITLE
TT and skull woods without gloves

### ISSUE THREAD

**Issue by kensykora** [wolfman2000/stumpy#82]
The map seems to think that Thives Town is accessible without the gloves or hammer, but with the hookshot. 

With aganam dead, to get there you need to use the temple warp, and then use the gloves to pick up the small skull on the east side of the river, and use the hookshot to get across the river. You can't access it with just hookshot.

![2018-07-01 15_08_29-window](https://user-images.githubusercontent.com/64756/42138326-3c808f92-7d41-11e8-8858-587b3c09f00b.png)

**Comment by wolfman2000** [comment]
Sorry for the delay. Let's see...no hammer, gloves are needed to lift that rock, no other dark world portal...yeah, I think you have found a bug.

**Comment by wolfman2000** [comment]
I am forced to make a correction. This is not a bug. You can use the flippers to swim up to the eastern shore, then move down and hookshot that way.

My apologies for the earlier rushed statement.

**Comment by jeremyZX** [comment]
Commenting on an old issue, but I encountered a variant of this using your tracker.  You can access TT and skull woods after Aga, with no gloves or flippers, but with Hookshot and Hammer.  In this state, your tracker only believes I can access TT and skull woods with Aga, Hookshot, and Flippers or Gloves.

![image](https://user-images.githubusercontent.com/634106/63215295-7f304800-c0f2-11e9-9b72-5dfa2f75b357.png)

From another tracker:

![image](https://user-images.githubusercontent.com/634106/63215346-27dea780-c0f3-11e9-803f-909616c81278.png)

The spot where you can hookshot, with rock and peg shown:

![image](https://user-images.githubusercontent.com/634106/63215296-8192a200-c0f2-11e9-8d47-8dfe6076193e.png)
