### ISSUE TITLE
Waterfall of Wishing showing as available without flippers

### ISSUE THREAD

**Issue by kensykora** [wolfman2000/stumpy#83]
![2018-07-01 22_26_03-window](https://user-images.githubusercontent.com/64756/42143962-ebdd2a54-7d7d-11e8-8639-951a69a1833f.png)

**Comment by wolfman2000** [comment]
Sorry for the delay. The waterfall of wishing is available, but you have to use Fake Flippers to access it.

If you notice the white border around the square, that indicates a minor glitch can be used.

Hope that helps.
