### ISSUE TITLE
TR Medallion Issue

### ISSUE THREAD

**Issue by lemabr01** [wolfman2000/stumpy#86]
Turtle Rock appears to erroneously mark itself as open under certain conditions, notably if the required medallion is Quake, you already possess Ether and Mire is listed as Ether.

Similarly if you have Quake it will not register as being open.

See attached images.

![image](https://user-images.githubusercontent.com/25397001/43500219-732d28ae-951d-11e8-962f-56e684c44fa2.png)

![image](https://user-images.githubusercontent.com/25397001/43500225-77b0e870-951d-11e8-8175-b76389097377.png)

**Comment by wolfman2000** [comment]
Closed by #89.
