### ISSUE TITLE
General upgrading/features issue list.

### ISSUE THREAD

**Issue by wolfman2000** [wolfman2000/stumpy#92]
I am due to try to upgrade this tracker with some wanted features, assuming there is enough interest. Consider this that interest poll.

* Some form of saving your progress in case of a browser crash, close, or refresh.
* Entrance Rando (May need to look into graph/vector based programming tips here).
* Better upgrade process to newer versions of the frameworks (apparently some of my tests break on webpack 4 now?).
* Better support for glitch modes.

Is it worth pursuing these, or is this mostly a done project?

**Comment by rosshadden** [comment]
I throw all of my votes (and all of the votes of the people that don't speak up!) at the first one. The only tracker I can use is crossproduct's firebase hosted one, as none of the other trackers I could find allow syncing.

I have to play runs in multiple sittings to work around life/work/responsibilities, and that tracker works great for this. You can "claim" a URL (like https://lttp-tracker.firebaseapp.com/foo), and then you can hit it from any computer or phone and update the same state.

**Comment by foxsouns** [comment]
first 2 for sure
